$(document).ready(function(){
	$("#1").click(function(){
		console.log(1);
		$("#grade").html("<h5>1</h5>");
	})
	$("#2").click(function(){
		$("#grade").html("<h5>2</h5>");
	})
	$("#3").click(function(){
		$("#grade").html("<h5>3</h5>");
	})
	$("#4").click(function(){
		$("#grade").html("<h5>4</h5>");
	})
	$("#5").click(function(){
		$("#grade").html("<h5>5</h5>");
	})
	$("#6").click(function(){
		$("#grade").html("<h5>6</h5>");
	})
	$("#7").click(function(){
		$("#grade").html("<h5>7</h5>");
	})
	$("#8").click(function(){
		$("#grade").html("<h5>8</h5>");
	})
	$("#9").click(function(){
		$("#grade").html("<h5>9</h5>");
	})
	$("#10").click(function(){
		$("#grade").html("<h5>10</h5>");
	})
})